# Generated by Django 4.0.4 on 2022-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('opt', models.CharField(max_length=100)),
                ('fileup', models.FileField(upload_to='Notesupload')),
                ('comments', models.TextField()),
            ],
        ),
    ]
